import moment from "moment-timezone";
export const NYLAS_AUTH_CONFIG = {
  storageType: "indexeddb",
  apiUri: process.env.NEXT_PUBLIC_NYLAS_API_URI || "https://api-staging.nylas.com",
  elementsApiUri: process.env.NEXT_PUBLIC_NYLAS_ELEMENTS_API_URI  || "https://elements-staging.us.nylas.com",
  clientId: process.env.NEXT_PUBLIC_NYLAS_CLIENT_ID || "nylas-client-id",
  defaultScopes: ["https://www.googleapis.com/auth/calendar"],
};
export const NYLAS_API_URL = process.env.NEXT_PUBLIC_NYLAS_API_URI || "https://api-staging.us.nylas.com";
export const NYLAS_SCHEDULER_API_URL = process.env.NEXT_PUBLIC_NYLAS_SCHEDULER_API_URL || "https://elements-staging.us.nylas.com";
export const FIREBASE_CONFIG = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  databaseURL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
}
export const FIREBASE_ADMIN_DATABASE_URL = process.env.FIREBASE_ADMIN_DATABASE_URL;
export const TIMEZONES: {
  [key: string]: string;
} = (() => {
  // List of all time zone names known to the Intl API
  const timeZones = moment.tz.names();

  return timeZones.reduce(
    (acc: { [key: string]: string }, timeZone: string) => {
      acc[timeZone] = timeZone.replace(/\//g, " / ");
      return acc;
    },
    {}
  );
})();
export const DURATIONS_AND_PRICES = [
  {
    duration: 30,
    price: 5,
  },
  {
    duration: 60,
    price: 10,
  },
];
export const BRAND_COLOR = "hsl(140, 75%, 50%)";
export const AUTH_COOKIE_NAME = "uprocket-demo-app";
export const SESSION_TIME_TO_LIVE = 5;
export const SKILLS = [
  "3D Animation",
  "3D Modeling",
  "3D Printing",
  "3D Rendering",
  "Accessibility Design",
  "Acoustics",
  "ADA Compliance",
  "Aquarium Exhibit Design",
  "Architectural Drawing",
  "Art Gallery Design",
  "Art Installation Design",
  "Art Selection",
  "Art Studio Design",
  "Artisanal Crafts",
  "ASP.NET",
  "Athletic Club Design",
  "Audiovisual Integration",
  "Audiovisual Systems",
  "Auditorium Design",
  "Augmented Reality Design",
  "Augmented Reality Integration",
  "AutoCAD",
  "Automotive Museum Design",
  "Aviation Museum Design",
  "Barware Design",
  "Bathroom Design",
  "Blueprint Reading",
  "Boardroom Design",
  "Botanical Garden Design",
  "Branding and Identity",
  "Brewery Design",
  "Buddhist Temple Design",
  "Budget Management",
  "Building Codes",
  "Building Information Modeling (BIM)",
  "C#",
  "C++",
  "Cabinetry Design",
  "CAD Conversion",
  "Carpentry",
  "Ceiling Design",
  "Children's Museum Design",
  "Church Interior Design",
  "Client Communication",
  "Co-Working Space Design",
  "Color Consulting",
  "Color Psychology",
  "Color Theory",
  "Commercial Design",
  "Commercial Interiors",
  "Commercial Kitchen Design",
  "Concept Development",
  "Conference Room Design",
  "Construction Administration",
  "Construction Documentation",
  "Convention Center Design",
  "Cost Estimation",
  "Craft Studio Design",
  "Dance Studio Design",
  "Dart",
  "Design Software (e.g., Photoshop, Illustrator)",
  "Disaster Preparedness",
  "Educational Facility Design",
  "Electrical Systems",
  "Energy Efficiency",
  "Energy-Efficient HVAC",
  "Environmental Design",
  "Equestrian Facility Design",
  "Ergonomic Furniture",
  "Ergonomic Office Furniture",
  "Ergonomics",
  "Event Design",
  "Event Planning",
  "Event Space Design",
  "Exhibit Design",
  "Exhibition Booth Design",
  "Fashion Museum Design",
  "Fashion Studio Design",
  "Feng Shui Design",
  "Film Museum Design",
  "Fire Safety",
  "Floor Coverings",
  "Floor Plan Design",
  "Food Museum Design",
  "Furniture Design",
  "Furniture Restoration",
  "Furniture Selection",
  "Game Room Design",
  "Garden Design",
  "Glasswork",
  "Go",
  "Golf Course Design",
  "Green Building Design",
  "Green Roof Design",
  "Hair Salon Design",
  "Healing Center Design",
  "Healthcare Design",
  "Hindu Temple Design",
  "Historic Preservation",
  "History Museum Design",
  "Home Automation",
  "Home Office Design",
  "Home Staging",
  "Home Theater Design",
  "Hospitality Design",
  "HVAC Systems",
  "Inclusive Design",
  "Industrial Design",
  "Interior Design",
  "Java",
  "JavaScript",
  "Kitchen Design",
  "Kotlin",
  "Landscape Design",
  "LEED Certification",
  "Lighting Control",
  "Lighting Design Software",
  "Lighting Design",
  "Lua",
  "Maker Space Design",
  "Maritime Museum Design",
  "Market Research",
  "Masonry",
  "Massage Therapy Studio Design",
  "Materials Selection",
  "Meditation Center Design",
  "Meditation Room Design",
  "Menu Design",
  "Metalwork",
  "Metalworking Shop Design",
  "Millwork Design",
  "Model Making",
  "Model Photography",
  "Mosque Interior Design",
  "Museum Exhibition Design",
  "Music Museum Design",
  "Music Studio Design",
  "Nail Salon Design",
  "Natural History Museum Design",
  "Objective-C",
  "Office Design",
  "Office Space Planning",
  "Perl",
  "Photography Studio Design",
  "Photography Styling",
  "PHP",
  "Pilates Studio Design",
  "Pilgrimage Retreat Design",
  "Planetarium Exhibit Design",
  "Plumbing Systems",
  "Pottery Studio Design",
  "Presentation Skills",
  "Product Design",
  "Project Management",
  "Project Scheduling",
  "Public Space Design",
  "Python",
  "Real Estate Staging",
  "Recording Studio Design",
  "Renovation Budgeting",
  "Renovation Planning",
  "Residential Design",
  "Residential Remodeling",
  "Restaurant & Bar Design",
  "Restaurant Layout Design",
  "Retail Design",
  "Revit",
  "Ruby",
  "Rust",
  "Sales Skills",
  "Scala",
  "Science Center Design",
  "Sculpture Design",
  "Sculpture Studio Design",
  "Security Systems",
  "Shell Scripting",
  "Signage Design",
  "Sikh Temple Design",
  "Site Analysis",
  "Sketching",
  "SketchUp",
  "Solar Panel Integration",
  "Soundproofing",
  "Spa Design",
  "Space Museum Design",
  "Space Planning",
  "Sports Facility Design",
  "Sports Museum Design",
  "SQL",
  "Sustainable Design",
  "Sustainable Landscaping",
  "Sustainable Lighting",
  "Sustainable Materials",
  "Swift",
  "Swimming Pool Design",
  "Synagogue Interior Design",
  "Tableware Design",
  "Technology Museum Design",
  "Temple Interior Design",
  "Temporary Exhibition Design",
  "Textile Design",
  "Textile Printing",
  "Theatre Set Design",
  "Time Management",
  "Trade Show Booth Design",
  "TypeScript",
  "Universal Design",
  "Upholstery",
  "Vendor Management",
  "Virtual Reality Design",
  "Virtual Reality Modeling",
  "Visual Merchandising",
  "Wall Treatments",
  "Wallpaper Design",
  "Water Conservation",
  "Wayfinding Design",
  "Wayfinding Signage",
  "Wedding Venue Design",
  "Wellness Center Design",
  "Window Treatments",
  "Wine Museum Design",
  "Winery Design",
  "Woodworking Shop Design",
  "Yoga Retreat Design",
  "Yoga Studio Design",
  "Zoo Exhibit Design",
  "SEO",
  "PPC",
  "Content Marketing",
  "Social Media Strategy",
  "Data Analysis",
  "Brand Development",
  "React",
  "Node.js",
  "Python",
  "Docker",
  "Kubernetes",
  "Agile Methodologies",
];
