/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PEPNdAbo8SC
 */
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { Header } from "./header";
import { Footer } from "./footer";
import Image from "next/image";

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen bg-white">
      <Header />
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6 mx-auto">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter text-apple-900sm:text-4xl md:text-5xl lg:text-6xl/none">
                  Hire the best contractors for any job
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl">
                  Connect with professionals from all over the world and get
                  your projects done efficiently and effectively.
                </p>
              </div>
              <div className="space-x-4">
                <Link
                  className="inline-flex h-9 items-center justify-center rounded-md bg-apple-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-apple-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-apple-950 disabled:pointer-events-none disabled:opacity-50:bg-apple-50/90:ring-apple-300"
                  href="#"
                >
                  Get Started
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-apple-50">
          <div className="container px-4 md:px-6  mx-auto">
            <div className="grid items-center gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
              <Image
                alt="Contractors"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <div className="inline-block rounded-lg bg-apple-300 px-3 py-1 text-sm">
                    Featured Services
                  </div>
                  <h2 className="text-3xl font-bold tracking-tighter text-apple-900sm:text-5xl">
                    A wide range of services for all your needs
                  </h2>
                  <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    From web development to graphic design, our contractors are
                    ready to help you with your projects.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-apple-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-apple-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-apple-950 disabled:pointer-events-none disabled:opacity-50:bg-apple-50/90:ring-apple-300"
                    href="#"
                  >
                    Browse Services
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10  mx-auto">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter text-apple-900sm:text-4xl md:text-5xl">
                What our clients say
              </h2>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Hear from our satisfied clients who have found success with our
                contractors.
              </p>
            </div>
            <div className="grid w-full grid-cols-1 md:grid-cols-2 lg:grid-cols-3 items-center justify-center gap-8 lg:gap-12 [&>img]:mx-auto">
              <Card>
                <CardContent>
                  <p className="text-sm leading-snug text-gray-500">
                    &quot;The freelancer I hired was professional and delivered
                    the project on time. I would definitely use UpRocket
                    again.&quot;
                  </p>
                  <div className="mt-4 text-sm font-medium text-apple-900">
                    - John Doe, CEO
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent>
                  <p className="text-sm leading-snug text-gray-500">
                    &quot;UpRocket made it easy to find a freelancer with the
                    skills I needed. The project was a success!&quot;
                  </p>
                  <div className="mt-4 text-sm font-medium text-apple-900">
                    - Jane Smith, Project Manager
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent>
                  <p className="text-sm leading-snug text-gray-500">
                    &quot;I was impressed with the quality of work from the
                    freelancer I hired on UpRocket. Highly recommended!&quot;
                  </p>
                  <div className="mt-4 text-sm font-medium text-apple-900">
                    - Sarah Johnson, Designer
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t bg-apple-50">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6  mx-auto">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter text-apple-900md:text-4xl/tight">
                Join our community of contractors
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Sign up to start connecting with clients and grow your freelance
                business.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex space-x-2">
                <Input
                  className="max-w-lg flex-1"
                  placeholder="Enter your email"
                  type="email"
                />
                <Button className="bg-apple-900 text-white" type="submit">
                  Sign Up
                </Button>
              </form>
              <p className="text-xs text-gray-500">
                By signing up, you agree to our
                <Link
                  className="underline underline-offset-2 text-apple-900"
                  href="#"
                >
                  Terms & Conditions
                </Link>
              </p>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
